"use strict";(()=>{var e={};e.id=1452,e.ids=[1452],e.modules={2885:e=>{e.exports=require("@supabase/supabase-js")},145:e=>{e.exports=require("next/dist/compiled/next-server/pages-api.runtime.prod.js")},6249:(e,r)=>{Object.defineProperty(r,"l",{enumerable:!0,get:function(){return function e(r,t){return t in r?r[t]:"then"in r&&"function"==typeof r.then?r.then(r=>e(r,t)):"function"==typeof r&&"default"===t?r:void 0}}})},7072:(e,r,t)=>{t.r(r),t.d(r,{config:()=>l,default:()=>c,routeModule:()=>p});var s={};t.r(s),t.d(s,{default:()=>d});var n=t(1802),a=t(7153),i=t(6249),o=t(3845),u=t(2972);async function d(e,r){if("GET"!==e.method)return r.status(405).json({error:"Method not allowed"});if(!(0,u.A)(e))return r.status(401).json({error:"Unauthorized"});try{let e=(0,o.p)(),{data:t,error:s}=await e.from("quiz_responses").select(`
        id,
        user_email,
        user_first_name,
        user_last_name,
        user_company,
        responses,
        created_at,
        ai_reports (
          id,
          report_status,
          access_token,
          email_sent_at,
          created_at,
          updated_at
        )
      `).order("created_at",{ascending:!1});if(s)return console.error("[ASSESSMENTS API] Error fetching assessments:",s),r.status(500).json({error:"Failed to fetch assessments",details:s.message});let n=t?.map(e=>{let r=e.ai_reports?.[0],t="Unknown";try{let r=e.responses;r?.industry&&(t=r.industry)}catch(e){console.error("Error parsing responses:",e)}return{id:e.id,userEmail:e.user_email,userFirstName:e.user_first_name||"",userLastName:e.user_last_name||"",userName:`${e.user_first_name||""} ${e.user_last_name||""}`.trim()||"Anonymous",company:e.user_company||"N/A",industry:t,status:r?.report_status||"pending",reportId:r?.id||null,accessToken:r?.access_token||null,emailSent:!!r?.email_sent_at,createdAt:e.created_at,reportCreatedAt:r?.created_at||null,reportUpdatedAt:r?.updated_at||null}})||[];r.status(200).json({assessments:n})}catch(e){console.error("Server error:",e),r.status(500).json({error:"Internal server error"})}}let c=(0,i.l)(s,"default"),l=(0,i.l)(s,"config"),p=new n.PagesAPIRouteModule({definition:{kind:a.x.PAGES_API,page:"/api/admin/assessments",pathname:"/api/admin/assessments",bundlePath:"",filename:""},userland:s})},2972:(e,r,t)=>{t.d(r,{A:()=>o,O:()=>i});let s=require("jsonwebtoken");var n=t.n(s);let a=process.env.ADMIN_JWT_SECRET||"your-secret-key-change-this-in-production";function i(){return n().sign({admin:!0,iat:Math.floor(Date.now()/1e3),exp:Math.floor(Date.now()/1e3)+86400},a)}function o(e){let r=e.cookies["admin-token"];if(!r)return!1;try{let e=n().verify(r,a);if(!0===e.admin)return!0;return!1}catch(e){return!1}}},3845:(e,r,t)=>{t.d(r,{O:()=>o,p:()=>u});var s=t(2885);let n="https://nwddsjghbyrerhhnciuk.supabase.co",a="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZGRzamdoYnlyZXJoaG5jaXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzIxMjMsImV4cCI6MjA2OTA0ODEyM30.8aXGuUq7occc15txLZJqQEYiLTKZNJ2Vsqb-oKh-g_U",i=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!n||!a)throw Error("Missing Supabase environment variables");let o=(0,s.createClient)(n,a),u=()=>{if(!i)throw Error("Missing SUPABASE_SERVICE_ROLE_KEY environment variable");return(0,s.createClient)(n,i,{auth:{autoRefreshToken:!1,persistSession:!1},db:{schema:"public"}})}},7153:(e,r)=>{var t;Object.defineProperty(r,"x",{enumerable:!0,get:function(){return t}}),function(e){e.PAGES="PAGES",e.PAGES_API="PAGES_API",e.APP_PAGE="APP_PAGE",e.APP_ROUTE="APP_ROUTE"}(t||(t={}))},1802:(e,r,t)=>{e.exports=t(145)}};var r=require("../../../webpack-api-runtime.js");r.C(e);var t=r(r.s=7072);module.exports=t})();