"use strict";(()=>{var e={};e.id=2678,e.ids=[2678],e.modules={2885:e=>{e.exports=require("@supabase/supabase-js")},145:e=>{e.exports=require("next/dist/compiled/next-server/pages-api.runtime.prod.js")},6249:(e,r)=>{Object.defineProperty(r,"l",{enumerable:!0,get:function(){return function e(r,t){return t in r?r[t]:"then"in r&&"function"==typeof r.then?r.then(r=>e(r,t)):"function"==typeof r&&"default"===t?r:void 0}}})},7538:(e,r,t)=>{t.r(r),t.d(r,{config:()=>l,default:()=>p,routeModule:()=>d});var n={};t.r(n),t.d(n,{default:()=>c});var o=t(1802),s=t(7153),a=t(6249),i=t(3845),u=t(2972);async function c(e,r){if("GET"!==e.method)return r.status(405).json({error:"Method not allowed"});if(!(0,u.A)(e))return r.status(401).json({error:"Unauthorized"});try{let e=(0,i.p)(),{data:t,error:n}=await e.from("mvp_planner_responses").select(`
        id,
        project_name,
        user_first_name,
        user_email,
        responses,
        completed_at,
        created_at,
        mvp_planner_reports (
          id,
          access_token,
          report_status,
          report_content
        )
      `).order("created_at",{ascending:!1});if(n)return console.error("Error fetching surveys:",n),r.status(500).json({error:"Failed to fetch surveys"});let o=t?.map(e=>{let r=e.mvp_planner_reports?.[0],t="Unknown",n="";if(r?.report_content)try{let e="string"==typeof r.report_content?JSON.parse(r.report_content):r.report_content;t=e.investment?.mvpPackage?.name||"Unknown",n=e.summary?.description||""}catch(e){console.error("Error parsing report content:",e)}let o="",s="";return e.responses&&(o=e.responses.platform||"",s=e.responses.targetUser||""),{id:e.id,projectName:e.project_name,userName:e.user_first_name||"Unknown",email:e.user_email,platform:o,targetUser:s,projectDescription:n,packageType:t,status:r?.report_status||"pending",reportToken:r?.access_token||null,completedAt:e.completed_at,createdAt:e.created_at}})||[];r.status(200).json({surveys:o})}catch(e){console.error("Error in surveys API:",e),r.status(500).json({error:"Internal server error"})}}let p=(0,a.l)(n,"default"),l=(0,a.l)(n,"config"),d=new o.PagesAPIRouteModule({definition:{kind:s.x.PAGES_API,page:"/api/admin/surveys",pathname:"/api/admin/surveys",bundlePath:"",filename:""},userland:n})},2972:(e,r,t)=>{t.d(r,{A:()=>i,O:()=>a});let n=require("jsonwebtoken");var o=t.n(n);let s=process.env.ADMIN_JWT_SECRET||"your-secret-key-change-this-in-production";function a(){return o().sign({admin:!0,iat:Math.floor(Date.now()/1e3),exp:Math.floor(Date.now()/1e3)+86400},s)}function i(e){let r=e.cookies["admin-token"];if(!r)return!1;try{let e=o().verify(r,s);if(!0===e.admin)return!0;return!1}catch(e){return!1}}},3845:(e,r,t)=>{t.d(r,{O:()=>i,p:()=>u});var n=t(2885);let o="https://nwddsjghbyrerhhnciuk.supabase.co",s="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZGRzamdoYnlyZXJoaG5jaXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzIxMjMsImV4cCI6MjA2OTA0ODEyM30.8aXGuUq7occc15txLZJqQEYiLTKZNJ2Vsqb-oKh-g_U",a=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!o||!s)throw Error("Missing Supabase environment variables");let i=(0,n.createClient)(o,s),u=()=>{if(!a)throw Error("Missing SUPABASE_SERVICE_ROLE_KEY environment variable");return(0,n.createClient)(o,a,{auth:{autoRefreshToken:!1,persistSession:!1},db:{schema:"public"}})}},7153:(e,r)=>{var t;Object.defineProperty(r,"x",{enumerable:!0,get:function(){return t}}),function(e){e.PAGES="PAGES",e.PAGES_API="PAGES_API",e.APP_PAGE="APP_PAGE",e.APP_ROUTE="APP_ROUTE"}(t||(t={}))},1802:(e,r,t)=>{e.exports=t(145)}};var r=require("../../../webpack-api-runtime.js");r.C(e);var t=r(r.s=7538);module.exports=t})();