"use strict";(()=>{var e={};e.id=6745,e.ids=[6745],e.modules={2885:e=>{e.exports=require("@supabase/supabase-js")},145:e=>{e.exports=require("next/dist/compiled/next-server/pages-api.runtime.prod.js")},6249:(e,r)=>{Object.defineProperty(r,"l",{enumerable:!0,get:function(){return function e(r,t){return t in r?r[t]:"then"in r&&"function"==typeof r.then?r.then(r=>e(r,t)):"function"==typeof r&&"default"===t?r:void 0}}})},5461:(e,r,t)=>{t.r(r),t.d(r,{config:()=>l,default:()=>u,routeModule:()=>c});var n={};t.r(n),t.d(n,{default:()=>p});var o=t(1802),s=t(7153),a=t(6249),i=t(3845);async function p(e,r){if("GET"!==e.method)return r.status(405).json({error:"Method not allowed"});try{let{token:t}=e.query;if(!t||"string"!=typeof t)return r.status(400).json({error:"Invalid token"});let n=(0,i.p)(),{data:o,error:s}=await n.from("mvp_planner_reports").select(`
        id,
        report_status,
        report_content,
        mvp_planner_response_id,
        created_at,
        mvp_planner_responses (
          user_email,
          user_first_name,
          project_name,
          responses,
          total_score,
          completed_at
        )
      `).eq("access_token",t).single();if(s||!o)return console.error("Error fetching report:",s),r.status(404).json({error:"Report not found"});let a=o.mvp_planner_responses;if(!a)return r.status(404).json({error:"Quiz response not found"});if("completed"===o.report_status&&o.report_content)try{let e="string"==typeof o.report_content?JSON.parse(o.report_content):o.report_content;r.status(200).json({status:"completed",content:e,userInfo:{email:a.user_email,firstName:a.user_first_name,projectName:a.project_name}})}catch(e){console.error("Error parsing report content:",e),r.status(500).json({error:"Invalid report content"})}else"failed"===o.report_status?r.status(200).json({status:"failed",error:"Report generation failed. Please try again.",userInfo:{email:a.user_email,firstName:a.user_first_name,projectName:a.project_name}}):r.status(200).json({status:o.report_status||"pending",userInfo:{email:a.user_email,firstName:a.user_first_name,projectName:a.project_name},responses:a.responses})}catch(e){console.error("Error in report endpoint:",e),r.status(500).json({error:"Failed to fetch report"})}}let u=(0,a.l)(n,"default"),l=(0,a.l)(n,"config"),c=new o.PagesAPIRouteModule({definition:{kind:s.x.PAGES_API,page:"/api/mvp-planner/report/[token]",pathname:"/api/mvp-planner/report/[token]",bundlePath:"",filename:""},userland:n})},3845:(e,r,t)=>{t.d(r,{O:()=>i,p:()=>p});var n=t(2885);let o="https://nwddsjghbyrerhhnciuk.supabase.co",s="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZGRzamdoYnlyZXJoaG5jaXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzIxMjMsImV4cCI6MjA2OTA0ODEyM30.8aXGuUq7occc15txLZJqQEYiLTKZNJ2Vsqb-oKh-g_U",a=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!o||!s)throw Error("Missing Supabase environment variables");let i=(0,n.createClient)(o,s),p=()=>{if(!a)throw Error("Missing SUPABASE_SERVICE_ROLE_KEY environment variable");return(0,n.createClient)(o,a,{auth:{autoRefreshToken:!1,persistSession:!1},db:{schema:"public"}})}},7153:(e,r)=>{var t;Object.defineProperty(r,"x",{enumerable:!0,get:function(){return t}}),function(e){e.PAGES="PAGES",e.PAGES_API="PAGES_API",e.APP_PAGE="APP_PAGE",e.APP_ROUTE="APP_ROUTE"}(t||(t={}))},1802:(e,r,t)=>{e.exports=t(145)}};var r=require("../../../../webpack-api-runtime.js");r.C(e);var t=r(r.s=5461);module.exports=t})();