"use strict";(()=>{var e={};e.id=3031,e.ids=[3031],e.modules={2885:e=>{e.exports=require("@supabase/supabase-js")},145:e=>{e.exports=require("next/dist/compiled/next-server/pages-api.runtime.prod.js")},6249:(e,t)=>{Object.defineProperty(t,"l",{enumerable:!0,get:function(){return function e(t,r){return r in t?t[r]:"then"in t&&"function"==typeof t.then?t.then(t=>e(t,r)):"function"==typeof t&&"default"===r?t:void 0}}})},9524:(e,t,r)=>{r.r(t),r.d(t,{config:()=>u,default:()=>l,routeModule:()=>p});var s={};r.r(s),r.d(s,{default:()=>c});var o=r(1802),a=r(7153),n=r(6249),i=r(3845);async function c(e,t){if("GET"!==e.method)return t.status(405).json({error:"Method not allowed"});let{reportId:r}=e.query;if(!r||"string"!=typeof r)return t.status(400).json({error:"Report ID required"});console.log("[STATUS] Checking status for report:",r);let s=(0,i.p)();try{let{data:e,error:o}=await s.from("ai_reports").select(`
        id,
        report_status,
        access_token,
        created_at,
        updated_at,
        email_sent_at,
        stage1_problem_analysis,
        stage2_tool_research,
        stage3_tool_selection,
        stage4_report_content
      `).eq("id",r).single();if(o||!e)return console.error("[STATUS] Report not found:",o),t.status(404).json({error:"Report not found"});let a=!!e.stage1_problem_analysis&&Object.keys(e.stage1_problem_analysis).length>0,n=!!e.stage2_tool_research&&Object.keys(e.stage2_tool_research).length>0,i=!!e.stage3_tool_selection&&Object.keys(e.stage3_tool_selection).length>0,c=!!e.stage4_report_content&&Object.keys(e.stage4_report_content).length>0,l={reportId:e.id,status:e.report_status,stage1_populated:a,stage2_populated:n,stage3_populated:i,stage4_populated:c,completed:"completed"===e.report_status,accessToken:e.access_token,emailSent:!!e.email_sent_at,createdAt:e.created_at,updatedAt:e.updated_at};"completed"===e.report_status&&e.access_token&&(l.reportUrl=`http://localhost:3000/report/view/${e.access_token}`),"failed"===e.report_status&&(l.errorMessage="Report generation failed. Please try again or contact support."),console.log("[STATUS] Returning status:",l.status,"Progress:",l.progress),t.status(200).json(l)}catch(e){console.error("[STATUS] Error checking report status:",e),t.status(500).json({error:"Failed to check report status",details:e instanceof Error?e.message:"Unknown error"})}}let l=(0,n.l)(s,"default"),u=(0,n.l)(s,"config"),p=new o.PagesAPIRouteModule({definition:{kind:a.x.PAGES_API,page:"/api/reports/status/[reportId]",pathname:"/api/reports/status/[reportId]",bundlePath:"",filename:""},userland:s})},3845:(e,t,r)=>{r.d(t,{O:()=>i,p:()=>c});var s=r(2885);let o="https://nwddsjghbyrerhhnciuk.supabase.co",a="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZGRzamdoYnlyZXJoaG5jaXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzIxMjMsImV4cCI6MjA2OTA0ODEyM30.8aXGuUq7occc15txLZJqQEYiLTKZNJ2Vsqb-oKh-g_U",n=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!o||!a)throw Error("Missing Supabase environment variables");let i=(0,s.createClient)(o,a),c=()=>{if(!n)throw Error("Missing SUPABASE_SERVICE_ROLE_KEY environment variable");return(0,s.createClient)(o,n,{auth:{autoRefreshToken:!1,persistSession:!1},db:{schema:"public"}})}},7153:(e,t)=>{var r;Object.defineProperty(t,"x",{enumerable:!0,get:function(){return r}}),function(e){e.PAGES="PAGES",e.PAGES_API="PAGES_API",e.APP_PAGE="APP_PAGE",e.APP_ROUTE="APP_ROUTE"}(r||(r={}))},1802:(e,t,r)=>{e.exports=r(145)}};var t=require("../../../../webpack-api-runtime.js");t.C(e);var r=t(t.s=9524);module.exports=r})();